import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#1E272E', 
    padding: 20,
  },
  header: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30, 
    marginTop: 25,
    width: '100%',
    paddingVertical: 10, 
    zIndex: 10,
  },
  titulo: {
    fontSize: 22, 
    fontWeight: '900',
    color: '#F39C12', 
    letterSpacing: 1,
    textAlign: 'center',
    width: '75%', 
  },
  subtituloHeader: {
    fontSize: 13,
    color: '#BDC3C7',
    fontWeight: '400',
    marginTop: 8, 
    textAlign: 'center',
  },
  botonHamburguesa: {
    position: 'absolute',
    left: 0,
    top: 0, 
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 99,
    elevation: 99,
  },
  rayasHamburguesa: {
    width: 24,
    height: 3,
    backgroundColor: '#F39C12',
    marginVertical: 2,
    borderRadius: 2,
  },
  card: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 8, 
    borderTopWidth: 6,
    borderTopColor: '#F39C12', 
    elevation: 4,
    marginBottom: 15, 
  },
  seccionTitulo: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#7F8C8D',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  label: {
    fontSize: 15,
    color: '#2C3E50',
    marginBottom: 6,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 6,
    padding: 10,
    fontSize: 16,
    marginBottom: 14,
    backgroundColor: '#F8FAFC',
    color: '#2C3E50',
  },
  separador: {
    height: 1.5,
    backgroundColor: '#ECF0F1',
    marginVertical: 14,
  },
  contenedorBotones: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  boton: {
    padding: 14,
    borderRadius: 6,
    alignItems: 'center',
    flex: 1,
  },
  botonCalcular: {
    backgroundColor: '#F39C12',
    marginRight: 6,
  },
  botonLimpiar: {
    backgroundColor: '#FFFFFF',
    marginLeft: 6,
    borderWidth: 2,
    borderColor: '#7F8C8D',
  },
  textoBoton: {
    fontSize: 15,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  textoBotonLimpiar: {
    fontSize: 15,
    fontWeight: '900',
    color: '#7F8C8D',
  },
  cardResultados: {
    backgroundColor: '#2C3E50', 
    padding: 20,
    borderRadius: 8,
    marginTop: 15,
    borderLeftWidth: 6,
    borderLeftColor: '#F39C12',
    marginBottom: 40, 
  },
  tituloResultados: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F39C12',
    marginBottom: 14,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  filaResultado: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#34495E',
  },
  textoResultado: {
    fontSize: 15,
    color: '#ECF0F1',
  },
  destacado: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#FFFFFF',
  },

  contenedorNotaSeguridad: {
    marginTop: 18,
    padding: 12,
    backgroundColor: 'rgba(231, 76, 60, 0.08)', 
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: '#E74C3C', 
  },
  tituloNotaSeguridad: {
    color: '#E74C3C', 
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  textoNotaSeguridad: {
    color: '#BDC3C7',
    fontSize: 11,
    textAlign: 'left',
    lineHeight: 16,
  },
});